name: Run Daily Script

on:
  schedule:
    - cron: '38 3 * * *'  # Runs daily at 9:00 AM IST (03:08 UTC)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install pandas yfinance requests

      - name: Run the script
        run: python Niftyopenvalues2.py
