# .github/workflows/daily-run.yml
name: Run Daily Script

on:
  schedule:
    - cron: '0 4 * * *'  # Runs daily at 9:08 AM IST (04:00 UTC)
  workflow_dispatch:     # Allows manual run

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Run the script
      run: python Niftyopenvalues2.py
